#! /bin/sh
#
# This file Autogenerated for cron02.waltham.manhunt.net by puppet. Hand edits considered harmful.
#
# $Id: groupchat_check.ini.erb,v 1.2 2011/02/08 16:47:46 wflynn Exp $
#
# Chatcheck Init File
#
# chkconfig: - 55 45
# description:	The chatcheck "daemon" reports active chat servers to memcache
# processname: groupchat_check.php
# config: /etc/sysconfig/chatcheck
# pidfile: /var/run/groupchat_check/groupchat_check.php.pid

# Source function library.
. /etc/rc.d/init.d/functions

#  Set some vars
APP_PATH=/usr/local/manhunt/cron
PATH=${PATH}:${APP_PATH}
PROCESSNAME=smtp_watcher.pl
RUNDIR=/var/run/smtp_db_watcher

start()
{
    echo -n $"Starting ${PROCESSNAME}: "
    /usr/bin/perl $APP_PATH/${PROCESSNAME} all 2>&1 1> /dev/null &
    RETVAL=$?
    echo $! > $RUNDIR/${PROCESSNAME}.pid
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/${PROCESSNAME}
}

stop()
{
    echo -n $"Stopping ${PROCESSNAME}: "
    killproc -p $RUNDIR/${PROCESSNAME}.pid ${PROCESSNAME}
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ] ; then
	rm -f /var/lock/subsys/${PROCESSNAME}
	rm -f $RUNDIR/${PROCESSNAME}.pid
    fi
}

restart () {
    stop
    sleep 1
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status ${PROCESSNAME}
	;;
    restart|reload)
	restart
	;;
    condrestart)
	[ -f /var/lock/subsys/${PROCESSNAME} ] && restart || :
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
	exit 1
esac

exit $?
