import "defines/*.pp"
import "classes/*.pp"

class ganglia {
 $latitude = extlookup("latitude")
 $longitude = extlookup("longitude")
 package { "ganglia-gmond": ensure => latest }

 file {"/etc/ganglia": ensure => directory }
 file {"/etc/ganglia/conf.d": ensure => directory, }
 file {"/etc/ganglia/gmond.conf":
  content => template("ganglia/gmond.conf.erb"),
  owner => "root", group => "root", mode => "0644",
  require => [Package["ganglia-gmond"],
              File["/etc/ganglia"],
              File["/etc/ganglia/conf.d"]],
  notify => Service["gmond"], }

  @@file {"/etc/ganglia/conf.d/${hostname}_gmond.conf":
    content => inline_template("#Automagically Generated by Puppet
data_source <%= datacenter.capitalize %> <%= fqdn %>"),
    owner => "root", group => "root", mode => "0644",
    tag => "host_gmond_conf", }
    

 nagmon::service {"gmond":
  enable => true, 
  ensure => running,
  pid_file => "/var/run/gmond.pid",
  init_script => "/etc/init.d/gmond",
  warn => "1:1",
  critical => "1:1",
  nrpe_parameter => "-C gmond",
  require => Package["ganglia-gmond"],
  subscribe => File["/etc/ganglia/gmond.conf"],}

}#end of class ganglia

