# Autogenerated for <%= fqdn %> by puppet
#
# $Id: app.yml.admin.tpl,v 1.90 2010/11/01 14:13:11 dcote Exp $
#
# Admin app.yml
#
# default values for all environments
#
all:
  #  Update on each deployment
  jsqstringsuffix: <%= js_version %>

  csrprofile: MANHUNTServiceMan
  enabledbretries: on
  entcachetime: '604800'
  exceptionCatcherFilter: on
  hivnoanswerdbid: 112
  mailcheckintervalinseconds: 60
  pagelogging: off
  profilecachetime: '3600'
  searchcachetime: 60
  shardsingleton: <%= shardsingleton %>
  skin: <%= skin %>
  theme: on
  tracklistsize: 50
  useimagecache: true
  


  uidlistmax: 300000
  .array:
    payway_ent_groups: ["payway", "paywayloc"]
    usorcanada: ["1297788", "1115370"]
  assetdirectory: /assets/admin/
  broadcastnotifylist: broadcast-notifications@online-buddies.com
  autoexternalmaileditor: off
  usespecialexternalmailserver: on
  externalmailserver: www.manhunt.net


  # Useful URLS
  twitter: http://twitter.com/manhunt
  facebook: http://www.facebook.com/manhunt
  openxserver: http://mh2.manhunt.net/
  partypixfeed: flickr.com/photos/manhuntnet

  ## Billing Settings
  billing: on
  ## Zero-Dollar Auths = "on", Full-Dollar Auths = "off"
  billingcreditcardpreauth: on
  billingfuturecreditcardpreauth: off
  ##
  billingboletopreauth: off
  billingecppreauth: on
  xmlrpc: https://billing-backend.v4.waltham.manhunt.net/billing/xmlRpcServer

  # Media
  media:
    codelocation: /usr/local/src/manhunt/  
    mount: /v4_media/

  menonline:
    hostname: dw02.waltham.manhunt.net
    dbname: manhunt
    user: apache
    password: LQSyM
    minmen: 20000

# ## SMARTFOX Chat
  chat:
    hostnames: ["im01.manhunt.net", "im02.manhunt.net", "im03.manhunt.net"]
    port: 443
    online_list_key: 'chat_servers_online'
    chat_on_for_all: true  
    ajax_ping_env: 'prod'
    ajax_ping_interval: 10
##

  multichat:
    hostnames: ["66.151.184.201"]

### Segregated Chat SYS-2043
  memcacheGeneral:
    host: 'cache07.waltham.manhunt.net:11215;cache02.waltham.manhunt.net:11215;cache03.v4.waltham.manhunt.net:11215'
 
  memcacheSessions:
    host: 'cache07.waltham.manhunt.net:11217;cache02.waltham.manhunt.net:11217;cache03.v4.waltham.manhunt.net:11217'
 
  memcacheEnt:
    host: 'cache07.waltham.manhunt.net:11213;cache02.waltham.manhunt.net:11213;cache03.v4.waltham.manhunt.net:11213'
 
  memcacheChat:
    host: 'cache08.waltham.manhunt.net:11219'

  memcacheImg:
    host: 'cache07.waltham.manhunt.net:11231'
 
  memcacheBilling:
    host: 'cache07.waltham.manhunt.net:11215;cache02.waltham.manhunt.net:11215;cache03.v4.waltham.manhunt.net:11215'

### END Segregated Chat


### DB Settings
  main:
    dsn: 'mysql:host=maindb00.v4.waltham.manhunt.net;dbname=manhunt_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  mainSlave:
    dsn: 'mysql:host=admindb00.v4.waltham.manhunt.net;dbname=manhunt_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

#search slave is not a seperate box, points to the mainSlave for now
  searchSlave:
    dsn: 'mysql:host=admindb00.v4.waltham.manhunt.net;dbname=manhunt_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  mail01:
    dsn: 'mysql:host=mailshard01b.waltham.manhunt.net;dbname=manhunt_mail_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  mail02:
    dsn: 'mysql:host=mailshard02.waltham.manhunt.net;dbname=manhunt_mail_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  mail03:
    dsn: 'mysql:host=mailshard03b.waltham.manhunt.net;dbname=manhunt_mail_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  mail04:
    dsn: 'mysql:host=mailshard04b.waltham.manhunt.net;dbname=manhunt_mail_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  reporting:
    dsn: 'mysql:host=dw03.waltham.manhunt.net;dbname=MANHAUS'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  profReporting:
    dsn: 'mysql:host=dw03.waltham.manhunt.net;dbname=MANHAUS'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  billingReporting:
    dsn: 'mysql:host=dw03.waltham.manhunt.net;dbname=MANHAUS'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  track:
    dsn: 'mysql:host=trackdb00.v4.waltham.manhunt.net;dbname=manhunt_tracklist_v4'
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>

  newBillingReporting:
    dsn: 'mysql:host=dw03.waltham.manhunt.net;dbname=manhunt_v4'
    user: manhunt
    password: manhunt2001

  SFLPSlave:
    dsn: 'mysql:host=mainsflp00.waltham.manhunt.net;dbname=manhunt_v4'   
    user: <%= scope.lookupvar("manhunt::params::mysql_app_user") %>
    password: <%= scope.lookupvar("manhunt::params::mysql_app_pw") %>
