class nagios::service::generic_service inherits nagios {
  nagios_service {"generic-service":
        ensure => present,
        name => "generic-service",
        service_description => "generic-service",
        contact_groups => it,
        check_period => "24x7",
        notification_period => "notify24x7",
        notification_options => "w,u,c,r",
        normal_check_interval => 5,
        max_check_attempts => 3,
        register => 1,
        active_checks_enabled => 1,
        passive_checks_enabled => 1,
        obsess_over_service => 1,
        check_freshness => 0,
        parallelize_check => 1,
        notifications_enabled => 1,
        event_handler_enabled => 1,
        flap_detection_enabled => 1,
        process_perf_data => 1,
        retry_check_interval => 1,
        notification_interval => 0,
        retain_status_information => 1,
        retain_nonstatus_information => 1,
        is_volatile => 0,
        failure_prediction_enabled => 1,
        }
}#end of the class nagios::service::generic_service
