#! /bin/bash

set -e
set -u

# This command will sync in progress work inside of vagrant
# to the local web server, making it available to other
# vagrant boxes.

echo '# Pipe this into bash -x'
echo rsync -avxHEP --delete \
  ~/vms/rpmsign/prosvc/ \
  /Library/WebServer/Documents/yum/prosvc/

